import assert from 'node:assert/strict';
import { createChatGPTAdapter } from '../adapters/chatgpt.js';
import { createConversationIndex } from '../core/index.js';
import { conversationIdentity, normalizeConversation } from '../models/conversation.js';
import { exportConversation } from '../export/pipeline.js';
import { createExportState, recordObservedVersion, recordSuccessfulExport, migrateLegacyState, recoverArtifact } from '../core/export-state.js';
import { fingerprintContent, observeContentVersion } from '../core/versioning.js';

const raw = { id: 'conv-1', title: 'Original', create_time: 1, update_time: 2, mapping: { root: { id: 'root', parent: null, children: ['user-node'], message: null }, 'user-node': { id: 'user-node', parent: 'root', children: ['assistant-node'], message: { id: 'm-user', author: { role: 'user' }, content: { content_type: 'text', parts: ['Fixture user text'] }, metadata: { attachments: [{ id: 'file-1', mime_type: 'application/pdf', name: 'notes.pdf', size: 12 }] } } }, 'assistant-node': { id: 'assistant-node', parent: 'user-node', children: ['tool-node'], message: { id: 'm-assistant', author: { role: 'assistant' }, content: { content_type: 'text', parts: ['Fixture assistant text'] } } }, 'tool-node': { id: 'tool-node', parent: 'assistant-node', children: [], message: { id: 'm-tool', author: { role: 'tool' }, content: { content_type: 'text', parts: ['hidden tool'] } } } } };
const adapter = createChatGPTAdapter({ list: async () => [raw], fetch: async () => raw });
assert.equal(await adapter.detect(), true);
const index = createConversationIndex(adapter);
const [item] = await index.list();
const conversation = await index.fetch(item);
assert.equal(item.identity, 'chatgpt:conv-1');
assert.equal(conversationIdentity({ ...conversation, title: 'Renamed' }), conversation.identity);
assert.equal(conversation.contentVersion, null);
const observed = observeContentVersion(conversation, { contentRevision: false });
assert.match(observed.value, /^fp128:/);
assert.equal(fingerprintContent({ ...conversation, title: 'Renamed' }), fingerprintContent(conversation));
assert.deepEqual(conversation.messages.map(m => m.role), ['user', 'assistant']);
assert.deepEqual(conversation.messages.map(m => m.content), ['Fixture user text', 'Fixture assistant text']);
assert.deepEqual(conversation.messages[0].attachments[0], { id: 'file-1', mimeType: 'application/pdf', name: 'notes.pdf', size: 12 });
const result = exportConversation(conversation, { capabilities: { contentRevision: false } });
const json = JSON.parse(result.json);
assert.equal(json.identity, result.manifest.identity);
assert.match(result.markdown, /Fixture user text/);
assert.match(result.markdown, /Fixture assistant text/);
assert.deepEqual(result.manifest.representations, ['json', 'markdown']);
assert.equal(result.manifest.attachmentManifest[0].id, 'file-1');
assert.equal(result.manifest.schemaVersion, 'chatharbor-export-state-v1');
assert.equal(result.manifest.contentVersion, observed.value);
assert.equal(json.contentVersion, observed.value);
let state = createExportState(conversation.identity);
assert.equal(state.status, 'never_exported');
state = recordObservedVersion(state, observed.value);
assert.equal(state.status, 'never_exported');
state = recordSuccessfulExport(state, { contentVersion: observed.value, exportedAt: '2026-09-12T00:00:00Z', representations: ['json'], artifactRefs: ['json-ref'] });
assert.equal(state.status, 'latest');
state = recordSuccessfulExport(state, { contentVersion: observed.value, exportedAt: '2026-09-12T00:01:00Z', representations: ['markdown'], artifactRefs: ['md-ref'] });
assert.deepEqual(state.exportedVersions[0].representations, ['json', 'markdown']);
assert.deepEqual(state.exportedVersions[0].artifactRefs, ['json-ref', 'md-ref']);
state = recordSuccessfulExport(state, { contentVersion: 'fp128:other', exportedAt: '2026-09-12T00:02:00Z', representations: ['json'], artifactRefs: ['other-ref'] });
assert.equal(state.exportedVersions.length, 2);
assert.equal(recordObservedVersion(state, 'fp:changed').status, 'has_updates');
assert.equal(recordObservedVersion({ ...state, currentObservedVersion: null }, null).status, 'unknown');
assert.equal(migrateLegacyState(conversation.identity, { exported: [conversation.identity] }).status, 'unknown');
assert.equal(migrateLegacyState(conversation.identity, { exported: [conversation.identity] }).legacyExported, true);
const recovered = recoverArtifact(createExportState(conversation.identity), { identity: conversation.identity, contentVersion: observed.value, representations: ['json'] });
assert.equal(recovered.exportedVersions[0].contentVersion, observed.value);
assert.deepEqual(recoverArtifact(createExportState(conversation.identity), { identity: 'other:id', contentVersion: observed.value }), createExportState(conversation.identity));
const native = observeContentVersion({ ...conversation, contentVersion: 'native-rev-1' }, { contentRevision: true });
assert.deepEqual(native, { value: 'native-rev-1', source: 'native', confidence: 'platform' });
assert.deepEqual(observeContentVersion({ ...conversation, messages: [] }, { contentRevision: false }).value, null);
console.log('vertical slice PASS');
