import assert from 'node:assert/strict';
import { createChatGPTAdapter } from '../adapters/chatgpt.js';
import { createConversationIndex } from '../core/index.js';
import { conversationIdentity, normalizeConversation } from '../models/conversation.js';
import { exportConversation } from '../export/pipeline.js';
import { createExportState, recordObservedVersion, recordSuccessfulExport, migrateLegacyState } from '../core/export-state.js';
import { fingerprintContent, observeContentVersion } from '../core/versioning.js';

const raw = { id: 'conv-1', title: 'Original', create_time: 1, update_time: 2, mapping: { root: { id: 'root', parent: null, children: ['user-node'], message: null }, 'user-node': { id: 'user-node', parent: 'root', children: ['assistant-node'], message: { id: 'm-user', author: { role: 'user' }, content: { content_type: 'text', parts: ['Fixture user text'] }, metadata: { attachments: [{ id: 'file-1', mime_type: 'application/pdf', name: 'notes.pdf', size: 12 }] } } }, 'assistant-node': { id: 'assistant-node', parent: 'user-node', children: ['tool-node'], message: { id: 'm-assistant', author: { role: 'assistant' }, content: { content_type: 'text', parts: ['Fixture assistant text'] } } }, 'tool-node': { id: 'tool-node', parent: 'assistant-node', children: [], message: { id: 'm-tool', author: { role: 'tool' }, content: { content_type: 'text', parts: ['hidden tool'] } } } } };
const adapter = createChatGPTAdapter({ list: async () => [raw], fetch: async () => raw });
assert.equal(await adapter.detect(), true);
const index = createConversationIndex(adapter);
const [item] = await index.list();
const conversation = await index.fetch(item);
assert.equal(item.identity, 'chatgpt:conv-1');
assert.equal(conversationIdentity({ ...conversation, title: 'Renamed' }), conversation.identity);
assert.equal(conversation.contentVersion, null);
const observed = observeContentVersion(conversation, { contentRevision: false });
assert.match(observed.value, /^fp:/);
assert.equal(fingerprintContent({ ...conversation, title: 'Renamed' }), fingerprintContent(conversation));
assert.deepEqual(conversation.messages.map(m => m.role), ['user', 'assistant']);
assert.deepEqual(conversation.messages.map(m => m.content), ['Fixture user text', 'Fixture assistant text']);
assert.deepEqual(conversation.messages[0].attachments[0], { id: 'file-1', mimeType: 'application/pdf', name: 'notes.pdf', size: 12 });
const result = exportConversation(conversation);
const json = JSON.parse(result.json);
assert.equal(json.identity, result.manifest.identity);
assert.match(result.markdown, /Fixture user text/);
assert.match(result.markdown, /Fixture assistant text/);
assert.deepEqual(result.manifest.representations, ['json', 'markdown']);
assert.equal(result.manifest.attachmentManifest[0].id, 'file-1');
assert.equal(result.manifest.schemaVersion, 'chatharbor-export-state-v1');
let state = createExportState(conversation.identity);
assert.equal(state.status, undefined);
state = recordObservedVersion(state, observed.value);
assert.equal(state.status, 'never_exported');
state = recordSuccessfulExport(state, { contentVersion: observed.value, exportedAt: '2026-09-12T00:00:00Z' });
assert.equal(state.status, 'latest');
assert.equal(recordObservedVersion(state, 'fp:changed').status, 'has_updates');
assert.equal(recordObservedVersion({ ...state, currentObservedVersion: null }, null).status, 'unknown');
assert.equal(migrateLegacyState(conversation.identity, { exported: [conversation.identity] }).status, 'unknown');
console.log('vertical slice PASS');
